// Enum types matching the frontend models
export enum WeaponType {
  SWORD = 'WEAPON_SWORD',
  CLAYMORE = 'WEAPON_CLAYMORE',
  POLEARM = 'WEAPON_POLEARM',
  BOW = 'WEAPON_BOW',
  CATALYST = 'WEAPON_CATALYST',
}

export enum ElementType {
  PYRO = 'ELEMENT_PYRO',
  HYDRO = 'ELEMENT_HYDRO',
  ELECTRO = 'ELEMENT_ELECTRO',
  CRYO = 'ELEMENT_CRYO',
  ANEMO = 'ELEMENT_ANEMO',
  GEO = 'ELEMENT_GEO',
  DENDRO = 'ELEMENT_DENDRO',
  NONE = 'NONE',
}

export enum QualityType {
  ORANGE = 'QUALITY_ORANGE',
  PURPLE = 'QUALITY_PURPLE',
  BLUE = 'QUALITY_BLUE',
}

export enum StatType {
  HP = 'FIGHT_PROP_HP',
  ATK = 'FIGHT_PROP_ATTACK',
  DEF = 'FIGHT_PROP_DEFENSE',
  CR = 'FIGHT_PROP_CRITICAL',
  CD = 'FIGHT_PROP_CRITICAL_HURT',
  ER = 'FIGHT_PROP_CHARGE_EFFICIENCY',
  EM = 'FIGHT_PROP_ELEMENT_MASTERY',
  PYRO_DMG = 'FIGHT_PROP_FIRE_ADD_HURT',
  HYDRO_DMG = 'FIGHT_PROP_WATER_ADD_HURT',
  ELECTRO_DMG = 'FIGHT_PROP_ELEC_ADD_HURT',
  CRYO_DMG = 'FIGHT_PROP_ICE_ADD_HURT',
  ANEMO_DMG = 'FIGHT_PROP_WIND_ADD_HURT',
  GEO_DMG = 'FIGHT_PROP_ROCK_ADD_HURT',
  DENDRO_DMG = 'FIGHT_PROP_GRASS_ADD_HURT',
  PHYSICAL_DMG = 'FIGHT_PROP_PHYSICAL_ADD_HURT',
  HEALING = 'FIGHT_PROP_HEAL_ADD',
  ATTACK_PERCENT = 'FIGHT_PROP_ATTACK_PERCENT',
}

export enum MaterialType {
  TALENT = 'MATERIAL_TALENT_LEVELING_UP',
  BOSS = 'MATERIAL_BOSS',
  GEMSTONE = 'MATERIAL_ELEMENTAL_STONE',
  LOCAL_SPECIALTY = 'MATERIAL_LOCAL_SPECIALTY',
  WEAPON = 'MATERIAL_WEAPON_PRIMARY_MATERIAL',
  GENERIC = 'MATERIAL_GENERIC',
  MOB = 'MATERIAL_MOB_DROP',
  COOKING = 'MATERIAL_COOKING',
}

export enum ArtifactType {
  FLOWER = 'EQUIP_BRACER',
  PLUME = 'EQUIP_NECKLACE',
  SANDS = 'EQUIP_SHOES',
  GOBLET = 'EQUIP_RING',
  CIRCLET = 'EQUIP_HEAD',
}
